FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest

EXPOSE 8080 2345

CMD ["sh", "-c", "go mod download && /go/bin/dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient --continue --only-same-user=false ."]
